name: Java Maven Build

on:
  push:
    branches:
      - master  # Trigger when pushing to the main branch

jobs:
  build:
    runs-on: [self-hosted, linux]  # Specify your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'  # Adoptium (OpenJDK 17)

    - name: Run Maven build
      run: mvn -B package --file pom.xml
