name: Java Maven Build and Docker Deployment

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch

jobs:
  build:
    runs-on: [self-hosted, linux]  # Specify your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'  # Adoptium (OpenJDK 17)

    - name: Run Maven build
      run: mvn -B package --file pom.xml

    - name: Build Docker image
      run: |
        # Assuming you have a Dockerfile in your repository to build the image
        docker build -t my-java-app .

    - name: Run Docker container
      run: |
        # Run the Docker container and expose the application on port 8080 (or any port you prefer)
        docker run -d -p 8080:8080 --name my-java-app-container my-java-app
