# This workflow will build a Java project with Maven and run the Docker container.

name: Java CI with Maven and Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted  # Use your self-hosted runner.

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Step to set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Step to build the project using Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml  # Build the JAR file

    # Step to build & push the Docker image
    - name: Build & Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: amanharsora543211/projectjava  # Your image name
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAMES }}  # Docker Hub username stored as a secret
        password: ${{ secrets.DOCKER_PASSWORDS }}  # Docker Hub password stored as a secret

    # Step to run the Docker container
    - name: Run Docker container
      run: |
        # Pull the Docker image from Docker Hub
        docker pull amanharsora543211/projectjava:latest
        
        # Stop and remove any running container with the same name (if any)
        docker stop my-java-container || true
        docker rm my-java-container || true

        # Run the Docker container
        docker run -d -p 8080:8080 --name my-java-container amanharsora543211/projectjava:latest

        # Step to configure AWS credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret access key
        aws-region: 'us-east-1'  # Specify your region

    # Step to configure kubectl to connect to your EKS cluster
    - name: Set up kubectl
      run: |
        # Install kubectl if not already installed
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.24.3/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Update kubeconfig for EKS cluster
      run: |
        aws eks --region us-east-1 update-kubeconfig --name my-cluster  # Replace with your EKS cluster name

    # Step to create Kubernetes deployment and service (using your Docker image)
    - name: Deploy Docker image to EKS
      run: |
        # Create Kubernetes deployment.yaml
        kubectl apply -f - <<EOF
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: java-app-deployment
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: java-app
          template:
            metadata:
              labels:
                app: java-app
            spec:
              containers:
              - name: java-container
                image: amanharsora543211/projectjava:latest  # Your image name
                ports:
                - containerPort: 8080
        EOF

        # Expose the deployment as a service
        kubectl expose deployment java-app-deployment --type=LoadBalancer --name=java-app-service --port=8080 --target-port=8080

    
    - name: Check deployment status
      run: |
        kubectl rollout status deployment/java-app-deployment
        kubectl get svc java-app-service
